Fix: Bugs to view nfts
boxfish-studio/sugar-rush pull request #135
Opened 2022-07-15 18:38 UTC by cpl121

## Changes

  - Fix error when no image
  - Fix error when findAllByCandyMachine fails
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

2022-07-18 09:30 UTC, VmMad requested changes

2022-07-18 09:30 UTC, VmMad commented on lib/nft/actions.ts
> +        const nfts: Nft[] = []
I think we should get rid of the for loop. Maybe nftsAddresses.map ?? [ ]

2022-07-18 13:59 UTC, cpl121 commented on lib/nft/actions.ts
>      if (!connection && !candyMachineAccount) return []
Perfect!

2022-07-19 11:11 UTC, evavirseda approved these changes
It looks good to me :rocket: 
sorry for the delay :pray:

2022-07-19 11:24 UTC, merged