Feat: upload delete popup
boxfish-studio/sugar-rush pull request #144
Opened 2022-07-19 16:17 UTC by cpl121

Fixes #110

## Changes

  - Add popup to delete candy machine
  - Move delete to popup
  - Functionality works
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

2022-07-20 08:34 UTC, evavirseda requested changes

2022-07-20 08:34 UTC, evavirseda commented on components/Popup.tsx
> +                    maxHeight: size === 'large' ? ['550px', '750px'] : ['27.5%'],
```suggestion
                    maxHeight: size === 'large' ? ['550px', '750px'] : ['40%', '27.5%'],
```

2022-07-20 08:34 UTC, evavirseda commented on components/DeleteCandyMachine.tsx
> +                {!isDeleting && status.message && (
:woozy_face: 
![image](https://user-images.githubusercontent.com/72078237/179936062-0c6728df-23d0-44e0-87c5-29b2da13917c.png)

2022-07-20 14:01 UTC, VmMad commented
![image](https://user-images.githubusercontent.com/88061365/180000836-aa387c48-e76c-4b71-8b2f-6bf0013d4f7e.png)
This is happening to me.
On low height screens this happens too... 
![image](https://user-images.githubusercontent.com/88061365/180001069-2e87f0c3-08a2-45ea-81e1-ad13c79fc535.png)
Change button title "Delete candy machine" to "Delete" 
Also, the disabled button when you click delete is bigger than the previous one, it looks a little weird

2022-07-20 14:05 UTC, cpl121 commented
> ![image](https://user-images.githubusercontent.com/88061365/180000836-aa387c48-e76c-4b71-8b2f-6bf0013d4f7e.png) This is happening to me. On low height screens this happens too... ![image](https://user-images.githubusercontent.com/88061365/180001069-2e87f0c3-08a2-45ea-81e1-ad13c79fc535.png) Change button title "Delete candy machine" to "Delete" Also, the disabled button when you click delete is bigger than the previous one, it looks a little weird

Yes, this is solved in [this pr](https://github.com/boxfish-studio/sugar-rush/pull/148) because the behavior is similar

2022-07-21 08:28 UTC, agus-xyz commented
please @cpl121 lets fix the conflicts with the base branch before proceeding with a final review 🙏🏼

2022-07-21 08:48 UTC, merged