Feat: update cm details
boxfish-studio/sugar-rush pull request #145
Opened 2022-07-20 10:46 UTC by evavirseda

Fixes #102 

## Changes

  - Update candy machine configuration to new design
  - Fix buttons size
  
### Checks

* [x] Have you catchup your branch with the latest state in base?
* [x] Have you lint your code locally prior to submission?
* [x] Have you reviewed your proposed changes and removed debris?
* [x] Have you successfully ran due tests with your changes?

2022-07-20 11:35 UTC, cpl121 commented on components/forms/UpdateCandyMachine.tsx
> +    const [errorMessage, setErrorMessage] = useState('')
`errorMessage` state is not being used

2022-07-20 11:45 UTC, cpl121 requested changes
Nice job!! just 2 comments

2022-07-20 14:05 UTC, VmMad commented
When you cancel the transaction you still get the message `Candy Machine updated successfully!`

2022-07-21 08:35 UTC, agus-xyz commented
looks good to me @evavirseda please lets fix the conflicts with base before proceeding to merge

2022-07-21 10:07 UTC, agus-xyz commented
@evavirseda it seems like the cm info in devnet broke after adding the selectable network. Do you think you can fix this yourself, or shall we ping @aspnxdd? 
![image](https://user-images.githubusercontent.com/3696240/180188672-a03dd357-737c-4bbb-8e47-afad70e44a86.png)

2022-07-21 10:10 UTC, evavirseda commented
> @evavirseda it seems like the cm info in devnet broke after adding the selectable network. Do you think you can fix this yourself, or shall we ping @aspnxdd? ![image](https://user-images.githubusercontent.com/3696240/180188672-a03dd357-737c-4bbb-8e47-afad70e44a86.png)

yes! I have already spoken with @aspnxdd , it seems that the first requests are for the mainnet RPC. He is working on it

2022-07-21 11:08 UTC, merged