feat: update candy machine preview NFTs to new design
boxfish-studio/sugar-rush pull request #170
Opened 2022-07-22 10:14 UTC by VmMad

Fixes #104

2022-07-22 10:21 UTC, cpl121 commented on pages/[id].tsx
> +                                                <h4>Unminted NFTs - {nfts.length}</h4>
I think that this value can be obtained from the same way as in the nfts header
`${itemsRemaining + mintedNfts.length}`

2022-07-22 10:22 UTC, cpl121 requested changes
Nice job!! 
Just one comment

2022-07-22 11:48 UTC, agus-xyz approved these changes
to me, it seems working, but I do not have a cache file to check our cms in mainnet. Could you @aspnxdd please check our cms? It should be easy to try with our cache files or?

2022-07-22 13:44 UTC, agus-xyz commented
for some reason, the `Upload Cache file` button is the only one that does not change the mouse on hover. Is this a bug or a feature? 
![image](https://user-images.githubusercontent.com/3696240/180451669-e835be41-8995-4b4c-88f9-e78651849ad2.png)
![image](https://user-images.githubusercontent.com/3696240/180451862-9af22931-f1f9-4723-b88f-15165ded01e7.png)

2022-07-22 16:10 UTC, evavirseda commented
> for some reason, the `Upload Cache file` button is the only one that does not change the mouse on hover. Is this a bug or a feature? ![image](https://user-images.githubusercontent.com/3696240/180451669-e835be41-8995-4b4c-88f9-e78651849ad2.png) ![image](https://user-images.githubusercontent.com/3696240/180451862-9af22931-f1f9-4723-b88f-15165ded01e7.png)

That's because it's not a button, `Upload Cache file` is an input, but we can add the hover effect

2022-07-22 17:12 UTC, VmMad commented
> for some reason, the `Upload Cache file` button is the only one that does not change the mouse on hover. Is this a bug or a feature? ![image](https://user-images.githubusercontent.com/3696240/180451669-e835be41-8995-4b4c-88f9-e78651849ad2.png) ![image](https://user-images.githubusercontent.com/3696240/180451862-9af22931-f1f9-4723-b88f-15165ded01e7.png)

I changed it already, you can check it out now. Other buttons weren't showing pointer either

2022-07-25 09:03 UTC, agus-xyz reviewed
I think it would be better having the nft preview reallocated just before the minted nfts. This way the user does not need to wait for the minted nfts to show in order to access the preview. I updated the design accordingly. What do you think?
![image](https://user-images.githubusercontent.com/3696240/180740044-9d949416-6a3a-4f16-b827-1876dbe18f3a.png)

2022-07-25 09:06 UTC, agus-xyz commented
@aspnxdd also suggested after testing, that in case the cache file does not have any nft (which might be the case sometimes), it should show `NFTs Preview not available in cache file` or something like that.

2022-07-26 09:56 UTC, evavirseda approved these changes
Nice :rocket: just confilcts!

2022-07-26 11:22 UTC, cpl121 approved these changes

2022-07-26 12:16 UTC, evavirseda commented
> @aspnxdd also suggested after testing, that in case the cache file does not have any nft (which might be the case sometimes), it should show `NFTs Preview not available in cache file` or something like that.

@agus-xyz this could be improve when we have notification system

2022-07-26 13:15 UTC, merged