Feat: display uploaded files
boxfish-studio/sugar-rush pull request #191
Opened 2022-07-26 09:15 UTC by cpl121

Fixes #177 

## Changes
  - Display uploaded files in create, update and verify candy machines
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

2022-07-26 10:19 UTC, evavirseda approved these changes
LGTM :rocket:

2022-07-27 07:55 UTC, begonaalvarezd requested changes
There are conflicts with the base branch 🙏🏼

2022-07-27 08:37 UTC, begonaalvarezd commented on pages/[id].tsx
> +                                    </div>
This code looks like it comes from a wrong merge 🙏🏼 can we please clean this up and just add the list of uploaded files?

2022-07-27 16:07 UTC, begonaalvarezd approved these changes

2022-07-27 16:07 UTC, merged