fix: all warnings in the project
boxfish-studio/sugar-rush pull request #237
Opened 2023-01-09 11:00 UTC by evavirseda

Depends on #236 
Fixes #233 

 
### Checks

* [x] Have you catchup your branch with the latest state in base?
* [x] Have you lint your code locally prior to submission?
* [x] Have you reviewed your proposed changes and removed debris?
* [x] Have you successfully ran due tests with your changes?

2023-01-17 14:46 UTC, begonaalvarezd requested changes
conflicts with base 🙏🏼

2023-01-17 18:19 UTC, cpl121 requested changes
Nice job, just 1 comment 💯

2023-01-17 18:19 UTC, cpl121 commented on components/Footer.tsx
> +                    Sugar Rush {version}
I receive this warn when starting the project
`warn  - ./components/Footer.tsx
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`

I think it is fixed as follows
`import version from '../version.json'` and `Sugar Rush {version.version}`

2023-01-19 10:19 UTC, cpl121 approved these changes
When making a yarn, I see that there are still some warnings, but I don't know if this task only focuses on linter warnings because they are in the task #229 group.
I approved the issue because I think that these warnings could be done in another task, to be able to close the #229
Nice job Eva 🥇

2023-01-25 10:15 UTC, begonaalvarezd approved these changes

2023-01-25 10:16 UTC, merged